FROM php:7-apache
COPY bootstrap-4.3.1 /var/www/html/bootstrap-4.3.1
COPY css /var/www/html/css
COPY js /var/www/html/js
COPY font-awesome-4.7.0 /var/www/html/font-awesome-4.7.0
COPY img /var/www/html/img
COPY jquery-3.4.1 /var/www/html/jquery-3.4.1
COPY popper-1.15.0 /var/www/html/popper-1.15.0 
COPY *.html /var/www/html/
